### ISSUE TITLE
'follow' crash

### ISSUE THREAD

**Issue by jonnyrobbie** [Hamuko/cum#47] opened 2017-05-27 23:35 UTC
I wanted to follow a series and got a crash:

```
cum follow http://bato.to/comic/_/comics/rozen-maiden-ii-r2656
Batoto username: JonnyRobbie
Batoto password: 
Traceback (most recent call last):
  File "/usr/bin/cum", line 11, in <module>
    load_entry_point('cum==0.8', 'console_scripts', 'cum')()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cum/cum.py", line 15, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cum/cum.py", line 209, in follow
    series = utility.series_by_url(url)
  File "/usr/lib/python3.6/site-packages/cum/utility.py", line 71, in series_by_url
    return Series(url)
  File "/usr/lib/python3.6/site-packages/cum/scrapers/batoto.py", line 18, in __init__
    self.chapters = self.get_chapters()
  File "/usr/lib/python3.6/site-packages/cum/scrapers/batoto.py", line 40, in get_chapters
    name = columns[0].img.next_sibling.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

$ cum --version
cum version 0.8 "Miyamo Chio"
```

**Comment by Hamuko** [comment] 2017-05-27 23:36
Duplicate of #46

**Comment by jonnyrobbie** [comment] 2017-05-27 23:36
yeah, I just noticed the duplicity...sorry about that

**Comment by Hamuko** [comment] 2017-05-27 23:36
No problem.

**Closed by Hamuko** 2017-05-27 23:36 UTC
Labels: duplicate
